export const todos = [
  {
    id: 0,
    assignee: { user: { id: 0, name: "Zipfelhuber" } },
    attachments: [],
    completed: false,
    dueTime: "28-09-2021",
    history: [],
    important: true,
    interval: 7,
    note: "Mach des gscheit!",
    reminder: "28-09-2021",
    text: "Kaffemaschine warten",
    subtasks: [
      {
        id: "0",
        text: "Auffangbehälter ausleeren",
        completed: false,
      },
      {
        id: "1",
        text: "Kaffeebohnen nachfüllen",
        completed: false,
      },
      {
        id: "2",
        text: "Wasserbehälter entkalten",
        completed: false,
      },
      {
        id: "3",
        text: "Wasserbehälter nachfüllen",
        completed: false,
      },
    ],
  },
  {
    id: 1,
    assignee: { user: { id: 0, name: "Zipfelheimer" } },
    attachments: [],
    completed: false,
    dueTime: "28-09-2021",
    history: [],
    important: true,
    interval: 7,
    note: "Mach wie du willst!",
    reminder: "28-09-2021",
    text: "Bad putzen",
    subtasks: [
      {
        id: "0",
        text: "Klo putzen",
        completed: false,
      },
      {
        id: "1",
        text: "Badewanne scheuern",
        completed: false,
      },
      {
        id: "2",
        text: "Guss entkalken",
        completed: false,
      },
      {
        id: "3",
        text: "Boden wischen",
        completed: false,
      },
    ],
  },
  {
    id: 2,
    assignee: { user: { id: 0, name: "Zipfelhauser" } },
    attachments: [],
    completed: false,
    dueTime: "28-10-2021",
    history: [],
    important: true,
    interval: 7,
    note: "Mach des ordentlich!",
    reminder: "28-10-2021",
    text: "Müll rausbringen",
    subtasks: [
      {
        id: "0",
        text: "Restmüll rausbringen",
        completed: false,
      },
      {
        id: "1",
        text: "Biomüll rausbringen",
        completed: false,
      },
      {
        id: "2",
        text: "Gelben Sack rausbringen",
        completed: false,
      },
      {
        id: "3",
        text: "Nuklearen Abfall rausbringen",
        completed: false,
      },
    ],
  },
];
